name: Playwright Cucumber CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  
  workflow_dispatch:  
    inputs:
      tags:
        description: "Cucumber tags (e.g. @Sanity)"
        required: false
        default: "@Sanity"

jobs:
  steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Set report name
        run: |
          TIMESTAMP = $(date } "%Y-%m-%d_%H-%M-%S")
          echo "REPORT_NAME=cucumber-report-${TIMESTAMP}-run-${GITHUB_RUN_NUMBER}" >> $GITBUG_ENV

      - name: Install dependencies
        run: npm ci  

      - name: Install Playwrigh Browsers
        run:  npx playwright install --with-deps   

      - name: Run Playwright Cucumber Tests
        run:  |
          TAGS="${{ github.event.inputs.tags || '@Sanity' }}"
          echo "Running tests with tags: $TAGS"

      - name: Generate HTML report
        if: always()
        run: npm run report  

      - name: Upload Test repository   
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.REPORT_NAME }}
          path: reports/